[language-server.rust-analyzer.config]
[language-server.rust-analyzer.config.check]
command = "clippy"
extraArgs = ["--" , "-W", "clippy::pedantic", "-A", "clippy::missing-errors-doc", "-A", "clippy::missing-panics-doc"]
